name = "wedding-spa-v2"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "EVENT_PHOTOS_BUCKET"
bucket_name = "event-photos"
preview_bucket_name = "event-photos"
